{% set name = "mashumaro" %}
{% set version = "3.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 3844137cf053bbac30c4cbd0ee9984e839a5731a0ef96fd3dd9388359af3f2e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.1.0

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.mixins
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
