{% set name = "mashumaro" %}
{% set version = "3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: bb4ff10aee689edff24f6ff369843e1a826193d396b449b86ef58489bfe40c83

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # Check for dependency changes at:
    # <https://github.com/Fatal1ty/mashumaro/blob/v{{ version }}/setup.py>
    - python >=3.7
    - typing-extensions >=4.1.0

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.mixins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
