{% set name = "mashumaro" %}
{% set version = "3.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 32a2a38a1e942a07f2cbf9c3061cb2a247714ee53e36a5958548b66bd116d0a9

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.1.0

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.mixins
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
