schema_version: 1

context:
  name: mashumaro
  version: "3.20"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mashumaro-${{ version }}.tar.gz
  sha256: af4573f14ae61be3fbc3a473158ddfc1420f345410385809fd782e0d79e9215c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.14.0

tests:
  - python:
      imports:
        - mashumaro
        - mashumaro.core
        - mashumaro.mixins
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Fatal1ty/mashumaro

extra:
  recipe-maintainers:
    - thewchan
    - maresb
